//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sesion01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Siteview = new HashSet<Siteview>();
        }
    
        public int id_contract { get; set; }
        public int device_id { get; set; }
        public int supplier_id { get; set; }
        public System.DateTime start_date { get; set; }
        public string contract_no { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Siteview> Siteview { get; set; }
    }
}
