//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int id_supplier { get; set; }
        public string business_name { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> IVA { get; set; }
    
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
